### ISSUE TITLE
README broken

### ISSUE THREAD

**Issue by Rebsos** [c0bra/deviceframe#13]
Markdown seems to be not recognized since the latest commit.

![readme](https://user-images.githubusercontent.com/17834477/38188569-cf4c6d0e-365c-11e8-9d53-cdc8b6105308.PNG)

When I roll back to the previous commit where the file is named 'README.md' instead of 'README' it works

**Comment by c0bra** [comment]
Bleh. I renamed it because it was broken on npm.  I'll revert and see how to fix it on npm without renaming.
