### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by jacobp100** [c0bra/deviceframe#14]
I'm working on a [project](https://github.com/jacobp100/react-image-export) that will be implementing framing like this. The gist is it renders react native apps to images without a simulator.

I wanted to add a `<Frame>` component so somebody could frame the screenshot, and then use other react native components to annotate it (screenshot titles etc.) You can see a gist [here](https://github.com/jacobp100/react-image-export/blob/master/packages/integration/index.snap.js)

To do this, it would be really handy to use your `frames.json` and `device-dimensions.json` files. However, the GPL license will make it hard for people to use this project. Would it be possible to re-licence this file with a permissive license like MIT?

**Comment by c0bra** [comment]
Yes I can so that

**Comment by c0bra** [comment]
@jacobp100 you should be good to go!

**Comment by jacobp100** [comment]
Thanks a lot! 🙏

**Comment by jacobp100** [comment]
Just to clarify, is `deviceframe-frames` just reusing Facebook's licence? I think it'll be easier to just use this repo so stuff is in sync 😀

**Comment by c0bra** [comment]
I searched and searched for Facebook's license on their frames and couldn't find anything.

The repo is separate to prevent unnecessary clutter. Not every frame is required for any particular person's needs.
