### ISSUE TITLE
stuck at download frame.

### ISSUE THREAD

**Issue by wispy316** [c0bra/deviceframe#18]
stuck at here.
(node:42467) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Downloading frame Apple Macbook Air 11" [shadow] [                    ] 50/bps 1% 2.0s

xingjiudeMBP:Downloads xj$ telnet 31.13.97.245 443
Trying 31.13.97.245...
can not getting any response.

![image](https://user-images.githubusercontent.com/4507261/43176087-cedd2466-8ff4-11e8-9348-cbcc12b23c1f.png)

visiting the https://www.mydevice.io/devices reports below:
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>E6C2C48A1D0E5037</RequestId>
<HostId>
yb3EfAMcLQqILZlHhWqC4dSEX4uDPUey/d6Q72bq7RL2oK4Behi1RwFNlgEqIY3Dt79FaUI4ArY=
</HostId>
</Error>

while 
https://cdn.rawgit.com/c0bra/deviceframe-frames/2.0.1/Computers/Apple%20Macbook%20Pro/15%22/Device/Apple%20Macbook%20Pro%2015%22.png
download fine. 

looks like the cdn is crashed, or my network problem.
any idea about this?

**Comment by c0bra** [comment]
Yea I think maybe the problem is on your end? I'm not seeing the same thing here.

What country are you connecting from?

**Comment by c0bra** [comment]
No response; closing
