### ISSUE TITLE
Add new devices

### ISSUE THREAD

**Issue by Tekl** [c0bra/deviceframe#8]
Like iPhone X or iPad Pro 10.5

**Comment by c0bra** [comment]
@Tekl if you can find some good quality frame images I will add them. Otherwise I will try to do it this week if possible.

**Comment by c0bra** [comment]
![iphone_x_frame](https://user-images.githubusercontent.com/105007/34920271-c67a699c-f935-11e7-9eba-af98cd4717bc.png)

maybe this one will work

**Comment by Tekl** [comment]
What about this one?
https://goodmockups.com/free-apple-ipad-pro-10-5-inches-tablet-psd-mockups/

**Comment by c0bra** [comment]
@Tekl we'd need to crop out the center, etc. Would you want the stylus included or no?

**Comment by Tekl** [comment]
Both variants would be the best, but I prefer the one without the pencil. Thanks for your great support.

**Comment by c0bra** [comment]
@Tekl sorry for taking so long to get around to this. I'm going to try to wrap it up this week.

**Comment by c0bra** [comment]
The iPad pro ones are in

**Comment by c0bra** [comment]
iPhone X is now in but the notch will be difficult to deal with.
